### ISSUE TITLE
App crash after initiating audio-casting on iOS: 'Invalid number value (infinite) in JSON write'

### ISSUE THREAD

**Issue by th3hamm0r** [miloproductionsinc/cordova-plugin-chromecast#11]
This issue kind of duplicates https://github.com/jellyfin/cordova-plugin-chromecast/issues/53, but I thought it better fits to your fork, since I've used your latest master. Also I've some additional information:

- I've used the code of your [example](https://github.com/miloproductionsinc/cordova-plugin-chromecast/blob/master/doc/example.js), but replaced the mp4-URL with an URL targeting a mp3-stream.
- The cast app gets started, so the `loadMedia`-Call seems to work on the remote device, but the app crashes before any of the `loadMedia`-callbacks are called.

**Comment by th3hamm0r** [comment]
Fyi: I've found the root cause and submitted a PR (https://github.com/miloproductionsinc/cordova-plugin-chromecast/pull/12)

**Comment by Lindsay-Needs-Sleep** [comment]
I have included your fix on my master, and submitted a PR to jellyfin!
Thanks again!
