### ISSUE TITLE
'@objc' method name provides one argument name, but method has 0 parameters

### ISSUE THREAD

**Issue by Mabudigital** [miloproductionsinc/cordova-plugin-chromecast#4]
Build failed with this error.

'@objc' method name provides one argument name, but method has 0 parameters in Chromecast.swift

 **@objc(checkReceiverAvailable:)**
 ```
@objc(checkReceiverAvailable:) 
func checkReceiverAvailable() {
    let sessionManager = GCKCastContext.sharedInstance().sessionManager

    if self.devicesAvailable.count > 0 || (sessionManager.currentSession != nil) {
        self.sendJavascript(jsCommand: "chrome.cast._.receiverAvailable()")
    } else {
        self.sendJavascript(jsCommand: "chrome.cast._.receiverUnavailable()")
    }

  }
```

**Comment by Lindsay-Needs-Sleep** [comment]
Sorry, I'm not really able to do ios fixes.  (No experience)

Would you be able to repost this issue in jellyfin issues? 
https://github.com/jellyfin/cordova-plugin-chromecast/issues

Is this a bug when you are using 1.0.0 branch?
If so, if you include "1.0.0" in the title that will be helpful.  
I will be issuing a pull request to jellyfin today I believe.  (So someone with ios experience can hopefully start helping with ios on 1.0.0.)

**Comment by Lindsay-Needs-Sleep** [comment]
(But, if no one is able to help soon, I will start learning objective C/Swift to help as well.  T.T)

**Comment by Lindsay-Needs-Sleep** [comment]
This code has been completely re-written (no more .swift files at all) so this issue can't exist anymore.
